#!/bin/bash
#PBS -W group_list=partner772
# The -W flag is mandatory and associates your job with your project group

# This tells PBS which queue you want to send your job to
# leaving it off will send it to the route queue

# Tells PBS what resources you require.
# There are two ways of doing this since this version of PBS Pro.

cd phd-code/quantphoto/
/etc/profile.d/modules.sh
module load fftw/3.3.3 petsc slepc
./3edge graphs/compleat out results/compleat 10 100
