#!/bin/bash
#PBS -W group_list=partner772
# The -W flag is mandatory and associates your job with your project group
# This tells PBS which queue you want to send your job to
# leaving it off will send it to the route queue
# Tells PBS what resources you require.
# There are two ways of doing this since this version of PBS Pro.

export MODULEPATH=$MODULEPATH:/group/partner772/software/modulefiles
cd phd-code/quantphoto/
/etc/profile.d/modules.sh
module load fftw/3.3.3 petsc slepc
mpirun -np 1 ./3edge graphs/22_1waycaly out results/22cly 22 100
